### ISSUE TITLE
Crash while trying to log uncaughtException

### ISSUE THREAD

**Issue by jrgm** [mozilla/mozlog#11]
```
{"Timestamp":1463009371241000000,"Logger":"fxa-basket-proxy",
 "Type":"uncaughtException","Severity":0,"Pid":15654,"EnvVersion":"2.0",
 "Fields":{"error":"TypeError: Cannot set property 'stack' of undefined","stack":"
    at HekaFormatter.hekaFormat [as format] (/data/fxa-basket-proxy/node_modules/mozlog/lib/format.js:94:22)
    at StreamHandler.format (/data/fxa-basket-proxy/node_modules/mozlog/node_modules/intel/lib/handlers/handler.js:52:28)
    at StreamHandler.streamEmit [as _emit] (/data/fxa-basket-proxy/node_modules/mozlog/node_modules/intel/lib/handlers/stream.js:21:27)
    at StreamHandler.emit (/data/fxa-basket-proxy/node_modules/mozlog/node_modules/intel/lib/handlers/handler.js:13:15)
    at Logger.handle (/data/fxa-basket-proxy/node_modules/mozlog/node_modules/intel/lib/logger.js:218:29)
    at Logger.handle (/data/fxa-basket-proxy/node_modules/mozlog/node_modules/intel/lib/logger.js:226:15)
    at Logger._log (/data/fxa-basket-proxy/node_modules/mozlog/node_modules/intel/lib/logger.js:249:20)
    at Logger.error (/data/fxa-basket-proxy/node_modules/mozlog/node_modules/intel/lib/logger.js:81:19)
    at Request.<anonymous> (/data/fxa-basket-proxy/lib/basket/index.js:19:14)
    at Request.emit (events.js:117:20)
    at null._onTimeout (/data/fxa-basket-proxy/node_modules/request/request.js:765:12)
    at Timer.listOnTimeout [as ontimeout] (timers.js:121:15)
"}}
```

**Comment by jrgm** [comment]
Which is this line https://github.com/mozilla/mozlog/blob/master/lib/format.js#L94

Don't offhand see how this is possible, but it happened.
