### ISSUE TITLE
Running mocha with MozLog break the stdout.

### ISSUE THREAD

**Issue by Natim** [mozilla/mozlog#4]
Expecting:

```
 2) websockets "after each" hook:

Uncaught AssertionError: expected 2 to deeply equal 3

at stopTest (/home/travis/build/mozilla-services/loop-server/test/websockets_test.js:867:39)
at WebSocket.<anonymous> (/home/travis/build/mozilla-services/loop-server/test/websockets_test.js:875:11)
at WebSocket.emit (events.js:117:20)
at WebSocket.cleanupWebsocketResources (/home/travis/build/mozilla-services/loop-server/node_modules/ws/lib/WebSocket.js:782:23)
at Socket.emit (events.js:117:20)
at _stream_readable.js:944:16
at process._tickCallback (node.js:442:13)
```

Receiving:

{"Timestamp":1420554568651000000,"Logger":"mozilla-loop-server","Type":"TypeError: undefined is not a function","Severity":0,"Pid":5937,"EnvVersion":"2.0"}

**Comment by vladikoff** [comment]
@Natim could you explain what is the expected output? are you using `console.log` or is something throwing an error and you want the error stack?

// cc @seanmonstar

**Comment by Natim** [comment]
@vladikoff The expected output is the one from mocha. It seams that MozLog prevent mocha from writting to stdout. I am not sure if mocha does catch the error and write it down directly or if it raises to write it down.

**Comment by seanmonstar** [comment]
Are you passing additional config to `mozlog`? What does mozlog output if you pass `pretty: true` in the config?
