### ISSUE TITLE
Unconstructive error message 'AssertionError: First arg must be op'

### ISSUE THREAD

**Issue by jrgm** [mozilla/mozlog#7]
The profile server on latest.dev.lcip.org was failing and continually restarting. In the error log was this unconstructive reason, converted from what was really going wrong (which is an invalid config setting I think).

```
assert.js:93
  throw new assert.AssertionError({
        ^
AssertionError: First arg must be op
    at Object.conf.filters.debug [as filter] (/data/fxa-profile-server/node_modules/mozlog/lib/index.js:42:16)
    at Logger.filter (/data/fxa-profile-server/node_modules/mozlog/node_modules/intel/lib/filterer.js:9:27)
    at Logger.handle (/data/fxa-profile-server/node_modules/mozlog/node_modules/intel/lib/logger.js:213:14)
    at Logger._log (/data/fxa-profile-server/node_modules/mozlog/node_modules/intel/lib/logger.js:249:20)
    at Logger.critical (/data/fxa-profile-server/node_modules/mozlog/node_modules/intel/lib/logger.js:81:19)
    at Logger.catchException (/data/fxa-profile-server/node_modules/mozlog/node_modules/intel/lib/logger.js:192:10)
    at process.emit (events.js:95:17)
    at process._fatalException (node.js:301:26)
```

**Comment by jrgm** [comment]
`record.args[0]` was `[TypeError: Cannot read property 'region' of undefined]`

**Comment by seanmonstar** [comment]
This is validation of the log arguments, so that the heka format can be created. The first argument must be a `String`, and will become part of the `op` of the record. I supposed a better message would be `First argument for log must be a String`?

**Comment by seanmonstar** [comment]
@jrgm I've improved the messages in https://github.com/mozilla/mozlog/commit/2ce17e7bbb3e8d843c834273eaebba2dfc89ad81

In this particular case, since the error came from `process.on('uncaughtException')`, mozlog will now properly adjust the record to fit.

In other cases, something like `logger.info({ foo: 'bar' })` will error with `AssertionError: logger.info(...) must take a String as first argument, got: { foo: 'bar' }`

**Comment by rfk** [comment]
sounds like this can be closed
